---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
	name: dataloader
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
	name: dataloader
spec:
	output:
		to:
			kind: ImageStreamTag
			name: dataloader:latest
	strategy:
		type: Docker
		dockerStrategy: {}
	source:
		type: Binary
		binary: {}
	triggers:
		- type: ConfigChange
		- type: ImageChange
